# -*- coding: utf-8 -*-
# Part of BP Optical POS. See LICENSE file for full copyright and licensing details.

{
    'name': 'BP Optical POS',
    'version': '17.0.2.0.2',
    'category': 'Point of Sale',
    'summary': 'Optical POS integration: optical tests, insurance payments, and analytics.',
    'author': 'Risolto Limited',
    'depends': [
        'point_of_sale',
        'account',
        'bp_optical_core',
    ],
    'data': [
        'security/bp_optical_pos_security.xml',
        'security/ir.model.access.csv',
        'data/insurance_journal.xml',
        'views/pos_optical_menu_views.xml',
        'views/stock_location_views.xml',
        'views/pos_config_optical_views.xml',
        'views/pos_payment_method_views.xml',
        'views/account_move_insurance_views.xml',
        'views/optical_branch_views.xml',
        'views/optical_optician_views.xml',
        'views/optical_test_views.xml',
        'views/res_config_settings_views.xml',
        'wizard/optical_branch_pl_wizard_views.xml',
        'report/pending_insurance_report.xml',
        'report/optical_branch_pl_report.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'bp_optical_pos/static/src/js/optical_insurance_popup.js',
            'bp_optical_pos/static/src/js/insurance_popup.js',
            'bp_optical_pos/static/src/js/insurance_payment_selection_popup.js',
            'bp_optical_pos/static/src/js/insurance_form_popup.js',
            'bp_optical_pos/static/src/js/optical_test_popup.js',
            'bp_optical_pos/static/src/js/optical_test_button.js',
            'bp_optical_pos/static/src/js/optical_models_ext.js',
            'bp_optical_pos/static/src/js/partner_editor_ext.js',
            'bp_optical_pos/static/src/js/partner_optical_history.js',
            'bp_optical_pos/static/src/js/stage_change_popup.js',
            'bp_optical_pos/static/src/js/test_stage_button.js',
            'bp_optical_pos/static/src/js/test_view_popup.js',
            'bp_optical_pos/static/src/xml/optical_insurance_popup.xml',
            'bp_optical_pos/static/src/xml/optical_test_popup.xml',
            'bp_optical_pos/static/src/xml/optical_test_button.xml',
            'bp_optical_pos/static/src/xml/insurance_popup.xml',
            'bp_optical_pos/static/src/xml/insurance_payment_selection_popup.xml',
            'bp_optical_pos/static/src/xml/insurance_form_popup.xml',
            'bp_optical_pos/static/src/xml/partner_editor_ext.xml',
            'bp_optical_pos/static/src/xml/partner_optical_history.xml',
            'bp_optical_pos/static/src/xml/stage_change_popup.xml',
            'bp_optical_pos/static/src/xml/test_stage_button.xml',
            'bp_optical_pos/static/src/xml/test_view_popup.xml',
        ],
    },
    'application': False,
    'installable': True,
    'license': 'LGPL-3',
}
